title: BAIN Lerntagebuch
author: Eva
description: > # this means to ignore newlines
  Lerntagebuch für das Fach Bibliotheks- und Archivinformatik (FS 2024)

# social links
github_username: eva-zk

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
